png(file="plot4.png")
par(mfrow=c(2,2))
plot(Mydata$Time,Mydata$Global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(Mydata$Time,Mydata$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(Mydata$Time,Mydata$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
points(Mydata$Time,Mydata$Sub_metering_2,type="l",col="red")
points(Mydata$Time,Mydata$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
plot(Mydata$Time,Mydata$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off(dev.cur())