png(file="plot3.png")
plot(Mydata$Time,Mydata$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
points(Mydata$Time,Mydata$Sub_metering_2,type="l",col="red")
points(Mydata$Time,Mydata$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
dev.off(dev.cur())